//! volta: Foundry PoC Solidity Test Synthesizer (.t.sol Generator)
//! Written in Pure Zig 0.16.0 with 0 Dynamic Heap Allocations.

const std = @import("std");
const fuzzer = @import("fuzzer.zig");

pub const MAX_POC_BUFFER_SIZE: usize = 32768; // 32KB Static PoC buffer

pub const FoundrySynthesizer = struct {
    poc_buffer: [MAX_POC_BUFFER_SIZE]u8 = [_]u8{0} ** MAX_POC_BUFFER_SIZE,
    poc_len: usize = 0,

    pub fn init() FoundrySynthesizer {
        return .{};
    }

    /// Synthesize a runnable Foundry .t.sol test from a failing TxSequence and invariant metadata
    pub fn synthesizePoC(
        self: *FoundrySynthesizer,
        test_name: []const u8,
        target_contract_hex: []const u8,
        seq: *const fuzzer.TxSequence,
        invariant_name: []const u8,
    ) []const u8 {
        var pos: usize = 0;
        const header = std.fmt.bufPrint(self.poc_buffer[pos..],
            \\// SPDX-License-Identifier: MIT
            \\pragma solidity ^0.8.20;
            \\
            \\import "forge-std/Test.sol";
            \\
            \\/// @notice Auto-Generated by Volta Bare-Silicon Invariant Engine
            \\/// @dev Reproduces Counterexample for Invariant: {s}
            \\contract {s}_ExploitPoC is Test {{
            \\    address target;
            \\    address attacker = address(0x1337);
            \\
            \\    function setUp() public {{
            \\        bytes memory bytecode = hex"{s}";
            \\        address deployed;
            \\        assembly {{
            \\            deployed := create(0, add(bytecode, 0x20), mload(bytecode))
            \\        }}
            \\        require(deployed != address(0), "Deployment failed");
            \\        target = deployed;
            \\        vm.deal(attacker, 1000 ether);
            \\    }}
            \\
            \\    function test_ReproduceCounterexample() public {{
            \\
        , .{ invariant_name, test_name, target_contract_hex }) catch return "";
        pos += header.len;

        for (0..seq.len) |step| {
            const call = seq.calls[step];
            const step_chunk = std.fmt.bufPrint(self.poc_buffer[pos..],
                \\        // Step {d}: Prank caller & execute call
                \\        vm.prank(address(0x{X:0>2}{X:0>2}));
                \\        (bool success_{d}, ) = target.call(
                \\            abi.encodeWithSelector(
                \\                bytes4(0x{X:0>2}{X:0>2}{X:0>2}{X:0>2}),
                \\                uint256(0x{X}),
                \\                uint256(0x{X}),
                \\                uint256(0x{X}),
                \\                uint256(0x{X})
                \\            )
                \\        );
                \\        assertTrue(success_{d}, "Step {d} execution failed");
                \\
            , .{
                step + 1,
                call.caller[0], call.caller[1],
                step + 1,
                call.selector[0], call.selector[1], call.selector[2], call.selector[3],
                call.args[0],
                call.args[1],
                call.args[2],
                call.args[3],
                step + 1, step + 1,
            }) catch return "";
            pos += step_chunk.len;
        }

        const footer = std.fmt.bufPrint(self.poc_buffer[pos..],
            \\        // Invariant '{s}' breached by stateful counterexample sequence.
            \\    }}
            \\}}
            \\
        , .{invariant_name}) catch return "";
        pos += footer.len;

        self.poc_len = pos;
        return self.poc_buffer[0..self.poc_len];
    }
};

test "Foundry Synth: Solidity PoC Generation" {
    var synth = FoundrySynthesizer.init();
    var seq = fuzzer.TxSequence.init();
    var call = fuzzer.TxCall{};
    call.selector = [_]u8{ 0xDE, 0xAD, 0xBE, 0xEF };
    call.args[0] = 1337;
    call.caller[0] = 0xAA;
    _ = seq.addCall(call);

    const poc = synth.synthesizePoC(
        "EulerVaultDonation",
        "6000F16103E860005500",
        &seq,
        "verifyConstantProduct",
    );

    try std.testing.expect(poc.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, poc, "EulerVaultDonation_ExploitPoC") != null);
    try std.testing.expect(std.mem.indexOf(u8, poc, "verifyConstantProduct") != null);
}
